name: Deploy Web App

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn theo dõi

jobs:
  deploy:
    runs-on: ubuntu-latest  # Có thể thay đổi hệ điều hành tùy theo yêu cầu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Chỉnh phiên bản Node.js nếu cần

      - name: Install dependencies
        run: npm install  # Cài đặt các phụ thuộc dự án

      - name: Build the project
        run: npm run build  # Nếu bạn có build step

      - name: Deploy to Server
        run: |
          scp -r ./dist username@your-server:/path/to/deploy  # Thay đổi lệnh này tùy theo cách bạn deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OPENAPI_KEY }}  # Nếu cần SSH Key hoặc bất kỳ bí mật nào
